# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ulefone/t1/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)
#$(shell mkdir -p $(OUT)/obj/STATIC_LIBRARIES/lib_driver_cmd_mt66xx_intermediates/ $(ANDROID_BUILD_TOP)/NOTICE-TARGET-STATIC_LIBRARIES-lib_driver_cmd_mt66xx)
#$(shell touch $(OUT)/obj/STATIC_LIBRARIES/lib_driver_cmd_mt66xx_intermediates/export_includes)
#$(shell cp $(ANDROID_BUILD_TOP)/device/ulefone/t1/mtk/lib_driver_cmd_mt66xx/arm64/lib_driver_cmd_mt66xx.a $(OUT)/obj/STATIC_LIBRARIES/lib_driver_cmd_mt66xx_intermediates/)
#$(shell cp -r $(ANDROID_BUILD_TOP)/device/ulefone/t1/mtk/lib_driver_cmd_mt66xx/ $(ANDROID_BUILD_TOP)/NOTICE-TARGET-STATIC_LIBRARIES-lib_driver_cmd_mt66xx)
#$(shell mkdir -p $(OUT)/obj_arm/SHARED_LIBRARIES/libaudiopolicymanager_intermediates/LINKED/ $(OUT)/obj_arm/SHARED_LIBRARIES/libaudiopolicymanager_intermediates/PACKED/ $(OUT)/obj/SHARED_LIBRARIES/libvtmal_intermediates/ $(OUT)/obj_arm/SHARED_LIBRARIES/libvtmal.so_intermediates/ $(OUT)/obj/lib)
#$(shell touch $(OUT)/obj_arm/SHARED_LIBRARIES/libvtmal.so_intermediates/export_includes $(OUT)/obj/SHARED_LIBRARIES/libvtmal_intermediates/export_includes $(OUT)/obj/lib/libvtmal.so.toc)
#$(shell cp $(LOCAL_PATH)/proprietary/lib/libaudiopolicymanager.so $(OUT)/obj_arm/SHARED_LIBRARIES/libaudiopolicymanager_intermediates/LINKED/libaudiopolicymanager.so)

$(shell mkdir -p $(OUT)/obj_arm/SHARED_LIBRARIES/libnvram_intermediates/ $(OUT)/obj_arm/lib/ $(OUT)/../../common/obj/JAVA_LIBRARIES/telephony-common_intermediates/)
$(shell touch $(OUT)/obj_arm/SHARED_LIBRARIES/libnvram_intermediates/export_includes $(OUT)/obj_arm/lib/libnvram.so.toc)
$(shell cp $(TOP)/frameworks/opt/magelib/legacy/ngin3d/com.mediatek.ja3m-static/target/javalib.jar $(OUT)/../../common/obj/JAVA_LIBRARIES/telephony-common_intermediates/)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
LOCAL_SRC_FILES := netutils.c
LOCAL_SHARED_LIBRARIES := libbinder libutils libril mtk-ril mtk-rilmd2 mtk-rilproxy librilproxy librilmtk
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := libshim_ril
LOCAL_CFLAGS := -O3 -Wno-unused-variable -Wno-unused-parameter
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
LOCAL_SRC_FILES := vtmal/mtk_vtmal.cpp
LOCAL_SHARED_LIBRARIES := libbinder libutils
LOCAL_MODULE_SUFFIX := .so
LOCAL_CFLAGS := -O3 -Wno-unused-variable -Wno-unused-parameter
LOCAL_MODULE := libshim_vtmal
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MULTILIB := both
LOCAL_MODULE := libaudiopolicymanager
LOCAL_SRC_FILES_32 := proprietary/lib/libaudiopolicymanager.so
LOCAL_SRC_FILES_64 := proprietary/lib64/libaudiopolicymanager.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libClearMotionFW
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libClearMotionFW.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libHEVCdec_sa.ca7.android
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libHEVCdec_sa.ca7.android.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libc2kril
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libc2kril.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libfgauge_gm30
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libfgauge_gm30.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libh264dec_customize
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libh264dec_customize.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libh264dec_sa.ca7
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libh264dec_sa.ca7.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libh264dec_sd.ca7
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libh264dec_sd.ca7.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libh264dec_se.ca7
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libh264dec_se.ca7.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libh264enc_sa.ca7
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libh264enc_sa.ca7.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libh264enc_sb.ca7
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libh264enc_sb.ca7.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libmjcFakeEngine
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libmjcFakeEngine.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libmp4enc_xa.ca7
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libmp4enc_xa.ca7.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libviagpsrpc
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libviagpsrpc.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := libviatelecom-withuim-ril
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libviatelecom-withuim-ril.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := librpcril
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/librpcril.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 32
LOCAL_MODULE := librpc
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/librpc.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MULTILIB := 64
LOCAL_MODULE := libipsec_ims_shr
LOCAL_SRC_FILES_64 := proprietary/vendor/lib64/libipsec_ims_shr.so
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := BtTool
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/vendor/app/BtTool/BtTool.apk
LOCAL_MODULE_PATH := vendor/app/BtTool
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := MDMConfig
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/vendor/app/MDMConfig/MDMConfig.apk
LOCAL_MODULE_PATH := vendor/app/MDMConfig
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := AgoldApnInfoCollector
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/AgoldApnInfoCollector/AgoldApnInfoCollector.apk
LOCAL_MODULE_PATH := system/app/AgoldApnInfoCollector
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := AgoldCompass
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/AgoldCompass/AgoldCompass.apk
LOCAL_MODULE_PATH := system/app/AgoldCompass
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := AgoldNetworkmanager
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/AgoldNetworkmanager/AgoldNetworkmanager.apk
LOCAL_MODULE_PATH := system/app/AgoldNetworkmanager
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := AguiAccAndAlspsCalibration
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/AguiAccAndAlspsCalibration/AguiAccAndAlspsCalibration.apk
LOCAL_MODULE_PATH := system/app/AguiAccAndAlspsCalibration
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := AosGpsTracker
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/AosGpsTracker/AosGpsTracker.apk
LOCAL_MODULE_PATH := system/app/AosGpsTracker
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Devicemessages114
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/Devicemessages114/Devicemessages114.apk
LOCAL_MODULE_PATH := system/app/Devicemessages114
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Devicemessages118
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/Devicemessages118/Devicemessages118.apk
LOCAL_MODULE_PATH := system/app/Devicemessages118
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GBoard
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/GBoard/GBoard.apk
LOCAL_MODULE_PATH := system/app/GBoard
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := IMEIApp
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/IMEIApp/IMEIApp.apk
LOCAL_MODULE_PATH := system/app/IMEIApp
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := agold.AgoldFactoryTest
LOCAL_PRIVILEGED_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/app/agold.AgoldFactoryTest/agold.AgoldFactoryTest.apk
LOCAL_MODULE_PATH := system/app/agold.AgoldFactoryTest
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GmsCore
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/priv-app/GmsCore/GmsCore.apk
LOCAL_MODULE_PATH := system/priv-app/GmsCore
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SimProcessor
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := proprietary/priv-app/SimProcessor/SimProcessor.apk
LOCAL_MODULE_PATH := system/priv-app/SimProcessor
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := agoldnvram
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/bin/agoldnvram
LOCAL_MODULE_PATH := system/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvram_proximity
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/bin/nvram_proximity
LOCAL_MODULE_PATH := system/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tee
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/bin/tee
LOCAL_MODULE_PATH := system/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := teed
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/bin/teed
LOCAL_MODULE_PATH := system/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := aee
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/aee
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := aee_archive
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/aee_archive
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := aee_core_forwarder
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/aee_core_forwarder
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := aee_dumpstate
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/aee_dumpstate
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := akmd09911
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/akmd09911
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := akmd8963
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/akmd8963
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := akmd8975
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/akmd8975
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ami304d
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/ami304d
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bmm050d
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/bmm050d
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := camtool
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/camtool
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ccci_fsd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/ccci_fsd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ccci_mdinit
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/ccci_mdinit
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emdlogger1
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/emdlogger1
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emdlogger2
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/emdlogger2
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emdlogger3
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/emdlogger3
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emdlogger5
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/emdlogger5
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := flashlessd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/flashlessd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := fuelgauged_nvram
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/fuelgauged_nvram
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ged_srv
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/ged_srv
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ipsec_mon
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/ipsec_mon
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libccu_bin.dm
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/libccu_bin.dm
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libccu_bin.pm
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/libccu_bin.pm
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := lsm303md
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/lsm303md
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := magd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/magd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mbimd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/mbimd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mc6420d
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/mc6420d
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := md_monitor
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/md_monitor
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := md_monitor_ctrl
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/md_monitor_ctrl
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mdlogger
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/mdlogger
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := memsicd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/memsicd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := memsicd3416x
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/memsicd3416x
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mfv_ut
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/mfv_ut
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mobile_log_d
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/mobile_log_d
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mtk_agpsd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/mtk_agpsd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mtkmal
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/mtkmal
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvram_daemon
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/nvram_daemon
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := qmcX983d
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/qmcX983d
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rs2spir
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/rs2spir
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rtt
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/rtt
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := s62xd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/s62xd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := slpd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/slpd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := spir2cl
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/spir2cl
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := statusd
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/statusd
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := sysenv_daemon
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/sysenv_daemon
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := thermal_manager
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/thermal_manager
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := thermalindicator
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/thermalindicator
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := viaradiooptions
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/viaradiooptions
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := viarild
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/viarild
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := volte_imcb
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/volte_imcb
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := volte_stack
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/volte_stack
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := volte_ua
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/volte_ua
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := wfca
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/wfca
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := wmt_concurrency
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/wmt_concurrency
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := wmt_launcher
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/wmt_launcher
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := wmt_loopback
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_SRC_FILES := proprietary/vendor/bin/wmt_loopback
LOCAL_MODULE_PATH := system/vendor/bin
include $(BUILD_PREBUILT)
